version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: energy_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: energy_lake
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-01-11T04-46-38Z
    container_name: energy_minio
    ports:
      - "9000:9000"       # API порт для Python
      - "9001:9001"       # Web-консоль
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    command: server /data --console-address ":9001"
    volumes:
      - miniodata:/data

volumes:
  pgdata:
  miniodata: